name: New meetup

env:
  MEETUP_FOLDER: './packages/site/src/content/meetups'
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]

jobs:
  new-meetup:
    runs-on: ubuntu-latest
    if: "contains( github.event.issue.labels.*.name, 'meetup' )"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-and-cache

      - uses: szenius/set-timezone@ce9c440bc3af4f51b28d7ef7e5c47ee8f26c8dcb # tag v1.2
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Create new meetup
        id: new_meetup
        run: |
          pnpm -r --filter=actions-new-meetup... install
          pnpm -r --filter=actions-new-meetup... run build
          pnpm -r --filter=actions-new-meetup run start
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        id: create_pr
        with:
          branch: ${{ steps.new_meetup.outputs.branch_name }}
          title: ${{ steps.new_meetup.outputs.pull_request_title }}
          body: ${{ steps.new_meetup.outputs.pull_request_body }}

      - name: Update comment
        run: |
          pnpm -r --filter=actions-post-create-pr... install
          pnpm -r --filter=actions-post-create-pr... run build
          pnpm -r --filter=actions-post-create-pr run start
        env:
          PULL_REQUEST_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
          COMMENT_ID: ${{ steps.new_meetup.outputs.comment_id }}
          GITHUB_TOKEN: ${{ github.token }}
